#网站默认使用语言
defaultContentLanguage: zh-cn

baseURL: http://example.org/

#指定语言代码
languageCode: zh-cn

#网站的题目
title: MoePunch 的网站

#指定主题
theme: stack

#启用Emoji
enableEmoji: true

#是否有汉语，日语，韩语，这可以使.summary和.wordcount正确作用
hasCJKLanguage: true

#版权信息
copyright: Copyright © MoePunch






module:
    hugoVersion:
        extended: true
        min: "0.87.0"

params:
    mainSections:
        - posts
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2023
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        compact: false
        emoji: 😈
        subtitle: 希君生羽翼，一化北溟鱼。
        avatar:
            enabled: true
            local: true
            src: img/head.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: 本文遵守 CC BY-NC-SA 4.0 协议

    comments:
        enabled: false
        provider: disqus

        disqusjs:
            shortname:
            apiUrl:
            apiKey:
            admin:
            adminLabel:

        utterances:
            repo:
            issueTerm: pathname
            label:

        remark42:
            host:
            site:
            locale:

        vssue:
            platform:
            owner:
            repo:
            clientId:
            clientSecret:
            autoCreateIssue: false

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL:
            lang:
            visitor:
            avatar:
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
            requiredMeta:
                - name
                - email
                - url
            placeholder:
            locale:
                admin: Admin

        twikoo:
            envId:
            region:
            path:
            lang:

        giscus:
            repo:
            repoID:
            category:
            categoryID:
            mapping:
            strict:
            lightTheme:
            darkTheme:
            reactionsEnabled: 1
            emitMetadata: 0
            inputPosition:
            lang:

        gitalk:
            owner:
            admin:
            repo:
            clientID:
            clientSecret:

        cusdis:
            host:
            id:

    widgets:
        homepage: []
        page: []

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true
